### PR TITLE
Implement summarizing from url

### PR DESCRIPTION
**Pull request by cacheflow**
-Allows a user to have an article summarized via URL.
-Included tests to ensure user passes a valid URL. 
-Updated Readme to explain usage.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Sorry for the delay in this!

I'm not sure if this really belongs at the package level. What do you think?

**Comment by fungilation** [comment]
Ya, I do this outside of package as would almost anyone else to source text to summarize. async fetch() is great by itself

**Comment by cacheflow** [comment]
I thought it would nice to add since people do it outside of the package all the time.

**Comment by jbrooksuk** [comment]
Thanks :)

**Comment by cacheflow** [comment]
Thanks! Could you also update this on NPM as well? I wanted to use it for a package I was working on. :D

**Pull request merged**
