### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by justinmchase**
I've tried to use this library a few times but it seems to be failing due to a few simple nodejs related issues. I hope this isn't taken the wrong way but I fixed it up!

What this fixes:
* Browser compatible
* Fixes the `import` token bug, which made it unusable as a dependency
* Adds build / watch / lint
* Fixes the lodash issue
* Added gulp 4, some basic tasks
* Updated babel and moved to env preset
* Libraries cannot use babel-register except during tests
* Cleaned up what gets included in the package
* Added standard linter
* Updated some syntax to es6, e.g. import, const, map, reduce, etc.
* Fixed an unreported bug in the giant unicode regexp
* Removed inconsistent, incorrectly patterned callback style from synchronous functions

I would recommend a Major version bump for this!

### CODE REVIEW

**Comment by justinmchase** [comment]
Fixes #40 #39 #37 #36 #31 #24 #12

**Comment by fungilation** [comment]
"Major" is right ^.^

Looks good, at a glance.

**Comment by CraigHarley** [comment]
Code looks good to me, I haven't tested it though.

**Comment by justinmchase** [comment]
Closing since no traction for a while.

**Comment by a-posteriori** [comment]
Code looks good, made similar changes before seeing this merge request, specifically the babel-env updates to work with browserify

**Pull request closed without merging**
